logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS

spring:
  rabbitmq:
    host: 192.168.154.131
    port: 5672
    username: root
    password: password
    virtual-host: /
    listener:
      simple:
        prefetch: 1