spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

#配置显示MP的标准输出
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#全局配置表前缀和id生成策略
#mybatis-plus:
#  global-config:
#    db-config:
#      table-prefix: tbl_
#      id-type: assign_id

